### ISSUE TITLE
能否请教一些编译项目时候遇到的问题？

### ISSUE THREAD

**Issue by Mr-Spade** [BruceWind/AESJniEncrypt#47]
我尝试使用gradle build命令编译您的项目，但是似乎遇到了一些麻烦QAQ

尝试自行解决了好久实在没有头绪，还希望作者能指点一下orz

这是执行gradle build以后给出的错误信息：

```
* What went wrong:
Execution failed for task ':aesjni:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process /home/saaaaalty/Android/Sdk/cmake/3.10.2.4988404/bin/ninja with arguments {-C /home/saaaaalty/Desktop/Dark/AESJniEncrypt/aesjni/.cxx/cmake/debug/armeabi-v7a JNIEncrypt}
  ninja: Entering directory `/home/saaaaalty/Desktop/Dark/AESJniEncrypt/aesjni/.cxx/cmake/debug/armeabi-v7a'
  
  ninja: error: '../../../../src/main/jni/sodium_include/libsodium-android-armv7-a/lib/libsodium.a', needed by '../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libJNIEncrypt.so', missing and no known rule to make it

```

不知道作者能否帮助我解决一下这个问题？

如果需要的话，这是在完整的信息：

```
> Configure project :aesjni
WARNING: Configuration 'androidTestCompile' is obsolete and has been replaced with 'androidTestImplementation'.
It will be removed in version 5.0 of the Android Gradle plugin.
For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.

> Configure project :app
WARNING: Configuration 'androidTestCompile' is obsolete and has been replaced with 'androidTestImplementation'.
It will be removed in version 5.0 of the Android Gradle plugin.
For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
WARNING: The specified Android SDK Build Tools version (25.0.3) is ignored, as it is below the minimum supported version (29.0.2) for Android Gradle Plugin 4.1.2.
Android SDK Build Tools 29.0.2 will be used.
To suppress this warning, remove "buildToolsVersion '25.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Task :aesjni:generateJsonModelDebug
/home/saaaaalty/Desktop/Dark/AESJniEncrypt/aesjni/CMakeLists.txt : C/C++ debug|armeabi-v7a : CMake Warning at /home/saaaaalty/Android/Sdk/ndk/21.1.6352462/build/cmake/android-legacy.toolchain.cmake:416 (message):
  An old version of CMake is being used that cannot automatically detect
  compiler attributes.  Compiler identification is being bypassed.  Some
  values may be wrong or missing.  Update to CMake 3.19 or newer to use
  CMake's built-in compiler identification.
Call Stack (most recent call first):
  /home/saaaaalty/Android/Sdk/ndk/21.1.6352462/build/cmake/android.toolchain.cmake:55 (include)
  .cxx/cmake/debug/armeabi-v7a/CMakeFiles/3.10.2/CMakeSystem.cmake:6 (include)
  CMakeLists.txt

/home/saaaaalty/Desktop/Dark/AESJniEncrypt/aesjni/CMakeLists.txt : C/C++ debug|armeabi-v7a : CMake Warning at /home/saaaaalty/Android/Sdk/ndk/21.1.6352462/build/cmake/android-legacy.toolchain.cmake:416 (message):
  An old version of CMake is being used that cannot automatically detect
  compiler attributes.  Compiler identification is being bypassed.  Some
  values may be wrong or missing.  Update to CMake 3.19 or newer to use
  CMake's built-in compiler identification.
Call Stack (most recent call first):
  /home/saaaaalty/Android/Sdk/ndk/21.1.6352462/build/cmake/android.toolchain.cmake:55 (include)
  .cxx/cmake/debug/armeabi-v7a/CMakeFiles/3.10.2/CMakeSystem.cmake:6 (include)
  CMakeLists.txt

/home/saaaaalty/Desktop/Dark/AESJniEncrypt/aesjni/CMakeLists.txt : C/C++ debug|arm64-v8a : CMake Warning at /home/saaaaalty/Android/Sdk/ndk/21.1.6352462/build/cmake/android-legacy.toolchain.cmake:416 (message):
  An old version of CMake is being used that cannot automatically detect
  compiler attributes.  Compiler identification is being bypassed.  Some
  values may be wrong or missing.  Update to CMake 3.19 or newer to use
  CMake's built-in compiler identification.
Call Stack (most recent call first):
  /home/saaaaalty/Android/Sdk/ndk/21.1.6352462/build/cmake/android.toolchain.cmake:55 (include)
  .cxx/cmake/debug/arm64-v8a/CMakeFiles/3.10.2/CMakeSystem.cmake:6 (include)
  CMakeLists.txt

/home/saaaaalty/Desktop/Dark/AESJniEncrypt/aesjni/CMakeLists.txt : C/C++ debug|arm64-v8a : CMake Warning at /home/saaaaalty/Android/Sdk/ndk/21.1.6352462/build/cmake/android-legacy.toolchain.cmake:416 (message):
  An old version of CMake is being used that cannot automatically detect
  compiler attributes.  Compiler identification is being bypassed.  Some
  values may be wrong or missing.  Update to CMake 3.19 or newer to use
  CMake's built-in compiler identification.
Call Stack (most recent call first):
  /home/saaaaalty/Android/Sdk/ndk/21.1.6352462/build/cmake/android.toolchain.cmake:55 (include)
  .cxx/cmake/debug/arm64-v8a/CMakeFiles/3.10.2/CMakeSystem.cmake:6 (include)
  CMakeLists.txt

/home/saaaaalty/Desktop/Dark/AESJniEncrypt/aesjni/CMakeLists.txt : C/C++ debug|x86 : CMake Warning at /home/saaaaalty/Android/Sdk/ndk/21.1.6352462/build/cmake/android-legacy.toolchain.cmake:416 (message):
  An old version of CMake is being used that cannot automatically detect
  compiler attributes.  Compiler identification is being bypassed.  Some
  values may be wrong or missing.  Update to CMake 3.19 or newer to use
  CMake's built-in compiler identification.
Call Stack (most recent call first):
  /home/saaaaalty/Android/Sdk/ndk/21.1.6352462/build/cmake/android.toolchain.cmake:55 (include)
  .cxx/cmake/debug/x86/CMakeFiles/3.10.2/CMakeSystem.cmake:6 (include)
  CMakeLists.txt

/home/saaaaalty/Desktop/Dark/AESJniEncrypt/aesjni/CMakeLists.txt : C/C++ debug|x86 : CMake Warning at /home/saaaaalty/Android/Sdk/ndk/21.1.6352462/build/cmake/android-legacy.toolchain.cmake:416 (message):
  An old version of CMake is being used that cannot automatically detect
  compiler attributes.  Compiler identification is being bypassed.  Some
  values may be wrong or missing.  Update to CMake 3.19 or newer to use
  CMake's built-in compiler identification.
Call Stack (most recent call first):
  /home/saaaaalty/Android/Sdk/ndk/21.1.6352462/build/cmake/android.toolchain.cmake:55 (include)
  .cxx/cmake/debug/x86/CMakeFiles/3.10.2/CMakeSystem.cmake:6 (include)
  CMakeLists.txt

/home/saaaaalty/Desktop/Dark/AESJniEncrypt/aesjni/CMakeLists.txt : C/C++ debug|x86_64 : CMake Warning at /home/saaaaalty/Android/Sdk/ndk/21.1.6352462/build/cmake/android-legacy.toolchain.cmake:416 (message):
  An old version of CMake is being used that cannot automatically detect
  compiler attributes.  Compiler identification is being bypassed.  Some
  values may be wrong or missing.  Update to CMake 3.19 or newer to use
  CMake's built-in compiler identification.
Call Stack (most recent call first):
  /home/saaaaalty/Android/Sdk/ndk/21.1.6352462/build/cmake/android.toolchain.cmake:55 (include)
  .cxx/cmake/debug/x86_64/CMakeFiles/3.10.2/CMakeSystem.cmake:6 (include)
  CMakeLists.txt

/home/saaaaalty/Desktop/Dark/AESJniEncrypt/aesjni/CMakeLists.txt : C/C++ debug|x86_64 : CMake Warning at /home/saaaaalty/Android/Sdk/ndk/21.1.6352462/build/cmake/android-legacy.toolchain.cmake:416 (message):
  An old version of CMake is being used that cannot automatically detect
  compiler attributes.  Compiler identification is being bypassed.  Some
  values may be wrong or missing.  Update to CMake 3.19 or newer to use
  CMake's built-in compiler identification.
Call Stack (most recent call first):
  /home/saaaaalty/Android/Sdk/ndk/21.1.6352462/build/cmake/android.toolchain.cmake:55 (include)
  .cxx/cmake/debug/x86_64/CMakeFiles/3.10.2/CMakeSystem.cmake:6 (include)
  CMakeLists.txt


> Task :aesjni:externalNativeBuildDebug FAILED
Build JNIEncrypt_armeabi-v7a
ninja: Entering directory `/home/saaaaalty/Desktop/Dark/AESJniEncrypt/aesjni/.cxx/cmake/debug/armeabi-v7a'
ninja: error: '../../../../src/main/jni/sodium_include/libsodium-android-armv7-a/lib/libsodium.a', needed by '../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libJNIEncrypt.so', missing and no known rule to make it

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':aesjni:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process /home/saaaaalty/Android/Sdk/cmake/3.10.2.4988404/bin/ninja with arguments {-C /home/saaaaalty/Desktop/Dark/AESJniEncrypt/aesjni/.cxx/cmake/debug/armeabi-v7a JNIEncrypt}
  ninja: Entering directory `/home/saaaaalty/Desktop/Dark/AESJniEncrypt/aesjni/.cxx/cmake/debug/armeabi-v7a'
  
  ninja: error: '../../../../src/main/jni/sodium_include/libsodium-android-armv7-a/lib/libsodium.a', needed by '../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libJNIEncrypt.so', missing and no known rule to make it


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2s
```

之前在运行编译前运行的shell脚本的时候，给出的部分警告信息如下：

```
Warnings related to headers being present but not usable are due to functions
that didn't exist in the specified minimum API version level.
They can be safely ignored.


Building for platform [android-16]

WARNING:__main__:make_standalone_toolchain.py is no longer necessary. The
$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin directory contains target-specific scripts that perform
the same task. For example, instead of:

    $ python $NDK/build/tools/make_standalone_toolchain.py \
        --arch arm --api 16 --install-dir toolchain
    $ toolchain/bin/clang++ src.cpp

Instead use:

    $ $NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi16-clang++ src.cpp

Traceback (most recent call last):
  File "/home/saaaaalty/Android/Sdk/ndk/23.1.7779620//build/tools/make_standalone_toolchain.py", line 377, in <module>
    main()
  File "/home/saaaaalty/Android/Sdk/ndk/23.1.7779620//build/tools/make_standalone_toolchain.py", line 361, in main
    create_toolchain(install_path, args.arch, api, toolchain_path, host_tag)
  File "/home/saaaaalty/Android/Sdk/ndk/23.1.7779620//build/tools/make_standalone_toolchain.py", line 224, in create_toolchain
    copy_tree(toolchain_path, install_path)
  File "/usr/lib/python2.7/distutils/dir_util.py", line 163, in copy_tree
    verbose=verbose, dry_run=dry_run))
  File "/usr/lib/python2.7/distutils/dir_util.py", line 163, in copy_tree
    verbose=verbose, dry_run=dry_run))
  File "/usr/lib/python2.7/distutils/dir_util.py", line 167, in copy_tree
    dry_run=dry_run)
  File "/usr/lib/python2.7/distutils/file_util.py", line 110, in copy_file
    "can't copy '%s': doesn't exist or not a regular file" % src)
distutils.errors.DistutilsFileError: can't copy '/home/saaaaalty/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/i686-linux-android/bin/as': doesn't exist or not a regular file
build-libsodium: built armv6!
```

**Comment by BruceWind** [comment]
编译需要 先拉取 libsodium 这个库的源码。脚本里已经都做好了。

**Comment by Mr-Spade** [comment]
感谢回复！脚本的部分信息我也放在issue的最下方了，如果需要的话，下面是完整的信息：

```
正克隆到 '/home/saaaaalty/Desktop/Dark/AESJniEncrypt/temp/libsodium'...
remote: Enumerating objects: 33224, done.
remote: Counting objects: 100% (832/832), done.
remote: Compressing objects: 100% (428/428), done.
remote: Total 33224 (delta 452), reused 702 (delta 388), pack-reused 32392
接收对象中: 100% (33224/33224), 8.75 MiB | 666.00 KiB/s, 完成.
处理 delta 中: 100% (19708/19708), 完成.
注意：正在切换到 '1.0.18'。

您正处于分离头指针状态。您可以查看、做试验性的修改及提交，并且您可以在切换
回一个分支时，丢弃在此状态下所做的提交而不对分支造成影响。

如果您想要通过创建分支来保留在此状态下所做的提交，您可以通过在 switch 命令
中添加参数 -c 来实现（现在或稍后）。例如：

  git switch -c <新分支名>

或者撤销此操作：

  git switch -

通过将配置变量 advice.detachedHead 设置为 false 来关闭此建议

HEAD 目前位于 4f5e89fa Don't ignore azure-pipelines.yml
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: creating directory build-aux
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: configure.ac: not using Autoheader
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:75: installing 'build-aux/compile'
configure.ac:9: installing 'build-aux/config.guess'
configure.ac:9: installing 'build-aux/config.sub'
configure.ac:10: installing 'build-aux/install-sh'
configure.ac:10: installing 'build-aux/missing'
src/libsodium/Makefile.am: installing 'build-aux/depcomp'
parallel-tests: installing 'build-aux/test-driver'
autoreconf: Leaving directory `.'

Warnings related to headers being present but not usable are due to functions
that didn't exist in the specified minimum API version level.
They can be safely ignored.


Building for platform [android-16]

WARNING:__main__:make_standalone_toolchain.py is no longer necessary. The
$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin directory contains target-specific scripts that perform
the same task. For example, instead of:

    $ python $NDK/build/tools/make_standalone_toolchain.py \
        --arch arm --api 16 --install-dir toolchain
    $ toolchain/bin/clang++ src.cpp

Instead use:

    $ $NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi16-clang++ src.cpp

Traceback (most recent call last):
  File "/home/saaaaalty/Android/Sdk/ndk/23.1.7779620//build/tools/make_standalone_toolchain.py", line 377, in <module>
    main()
  File "/home/saaaaalty/Android/Sdk/ndk/23.1.7779620//build/tools/make_standalone_toolchain.py", line 361, in main
    create_toolchain(install_path, args.arch, api, toolchain_path, host_tag)
  File "/home/saaaaalty/Android/Sdk/ndk/23.1.7779620//build/tools/make_standalone_toolchain.py", line 224, in create_toolchain
    copy_tree(toolchain_path, install_path)
  File "/usr/lib/python2.7/distutils/dir_util.py", line 163, in copy_tree
    verbose=verbose, dry_run=dry_run))
  File "/usr/lib/python2.7/distutils/dir_util.py", line 163, in copy_tree
    verbose=verbose, dry_run=dry_run))
  File "/usr/lib/python2.7/distutils/dir_util.py", line 167, in copy_tree
    dry_run=dry_run)
  File "/usr/lib/python2.7/distutils/file_util.py", line 110, in copy_file
    "can't copy '%s': doesn't exist or not a regular file" % src)
distutils.errors.DistutilsFileError: can't copy '/home/saaaaalty/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/i686-linux-android/bin/as': doesn't exist or not a regular file
build-libsodium: built armv6!

Warnings related to headers being present but not usable are due to functions
that didn't exist in the specified minimum API version level.
They can be safely ignored.


Building for platform [android-16]

WARNING:__main__:make_standalone_toolchain.py is no longer necessary. The
$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin directory contains target-specific scripts that perform
the same task. For example, instead of:

    $ python $NDK/build/tools/make_standalone_toolchain.py \
        --arch arm --api 16 --install-dir toolchain
    $ toolchain/bin/clang++ src.cpp

Instead use:

    $ $NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi16-clang++ src.cpp

Traceback (most recent call last):
  File "/home/saaaaalty/Android/Sdk/ndk/23.1.7779620//build/tools/make_standalone_toolchain.py", line 377, in <module>
    main()
  File "/home/saaaaalty/Android/Sdk/ndk/23.1.7779620//build/tools/make_standalone_toolchain.py", line 361, in main
    create_toolchain(install_path, args.arch, api, toolchain_path, host_tag)
  File "/home/saaaaalty/Android/Sdk/ndk/23.1.7779620//build/tools/make_standalone_toolchain.py", line 224, in create_toolchain
    copy_tree(toolchain_path, install_path)
  File "/usr/lib/python2.7/distutils/dir_util.py", line 163, in copy_tree
    verbose=verbose, dry_run=dry_run))
  File "/usr/lib/python2.7/distutils/dir_util.py", line 163, in copy_tree
    verbose=verbose, dry_run=dry_run))
  File "/usr/lib/python2.7/distutils/dir_util.py", line 167, in copy_tree
    dry_run=dry_run)
  File "/usr/lib/python2.7/distutils/file_util.py", line 110, in copy_file
    "can't copy '%s': doesn't exist or not a regular file" % src)
distutils.errors.DistutilsFileError: can't copy '/home/saaaaalty/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/i686-linux-android/bin/as': doesn't exist or not a regular file
build-libsodium: built armv7-a!

Warnings related to headers being present but not usable are due to functions
that didn't exist in the specified minimum API version level.
They can be safely ignored.


Building for platform [android-16]

usage: make_standalone_toolchain.py [-h] --arch {arm,arm64,x86,x86_64}
                                    [--api API] [--stl STL] [--force] [-v]
                                    [--package-dir PACKAGE_DIR | --install-dir INSTALL_DIR]
make_standalone_toolchain.py: error: argument --arch: invalid choice: 'mips' (choose from 'arm', 'arm64', 'x86', 'x86_64')
build-libsodium: built mips32!

Warnings related to headers being present but not usable are due to functions
that didn't exist in the specified minimum API version level.
They can be safely ignored.


Building for platform [android-16]

WARNING:__main__:make_standalone_toolchain.py is no longer necessary. The
$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin directory contains target-specific scripts that perform
the same task. For example, instead of:

    $ python $NDK/build/tools/make_standalone_toolchain.py \
        --arch x86 --api 16 --install-dir toolchain
    $ toolchain/bin/clang++ src.cpp

Instead use:

    $ $NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android16-clang++ src.cpp

Traceback (most recent call last):
  File "/home/saaaaalty/Android/Sdk/ndk/23.1.7779620//build/tools/make_standalone_toolchain.py", line 377, in <module>
    main()
  File "/home/saaaaalty/Android/Sdk/ndk/23.1.7779620//build/tools/make_standalone_toolchain.py", line 361, in main
    create_toolchain(install_path, args.arch, api, toolchain_path, host_tag)
  File "/home/saaaaalty/Android/Sdk/ndk/23.1.7779620//build/tools/make_standalone_toolchain.py", line 224, in create_toolchain
    copy_tree(toolchain_path, install_path)
  File "/usr/lib/python2.7/distutils/dir_util.py", line 163, in copy_tree
    verbose=verbose, dry_run=dry_run))
  File "/usr/lib/python2.7/distutils/dir_util.py", line 163, in copy_tree
    verbose=verbose, dry_run=dry_run))
  File "/usr/lib/python2.7/distutils/dir_util.py", line 167, in copy_tree
    dry_run=dry_run)
  File "/usr/lib/python2.7/distutils/file_util.py", line 110, in copy_file
    "can't copy '%s': doesn't exist or not a regular file" % src)
distutils.errors.DistutilsFileError: can't copy '/home/saaaaalty/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/i686-linux-android/bin/as': doesn't exist or not a regular file
build-libsodium: built x86!

Warnings related to headers being present but not usable are due to functions
that didn't exist in the specified minimum API version level.
They can be safely ignored.


Building for platform [android-21]

WARNING:__main__:make_standalone_toolchain.py is no longer necessary. The
$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin directory contains target-specific scripts that perform
the same task. For example, instead of:

    $ python $NDK/build/tools/make_standalone_toolchain.py \
        --arch arm64 --api 21 --install-dir toolchain
    $ toolchain/bin/clang++ src.cpp

Instead use:

    $ $NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++ src.cpp

Traceback (most recent call last):
  File "/home/saaaaalty/Android/Sdk/ndk/23.1.7779620//build/tools/make_standalone_toolchain.py", line 377, in <module>
    main()
  File "/home/saaaaalty/Android/Sdk/ndk/23.1.7779620//build/tools/make_standalone_toolchain.py", line 361, in main
    create_toolchain(install_path, args.arch, api, toolchain_path, host_tag)
  File "/home/saaaaalty/Android/Sdk/ndk/23.1.7779620//build/tools/make_standalone_toolchain.py", line 224, in create_toolchain
    copy_tree(toolchain_path, install_path)
  File "/usr/lib/python2.7/distutils/dir_util.py", line 163, in copy_tree
    verbose=verbose, dry_run=dry_run))
  File "/usr/lib/python2.7/distutils/dir_util.py", line 163, in copy_tree
    verbose=verbose, dry_run=dry_run))
  File "/usr/lib/python2.7/distutils/dir_util.py", line 167, in copy_tree
    dry_run=dry_run)
  File "/usr/lib/python2.7/distutils/file_util.py", line 110, in copy_file
    "can't copy '%s': doesn't exist or not a regular file" % src)
distutils.errors.DistutilsFileError: can't copy '/home/saaaaalty/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/i686-linux-android/bin/as': doesn't exist or not a regular file
build-libsodium: built armv8-a!
mv: 无法获取'/home/saaaaalty/Desktop/Dark/AESJniEncrypt/temp/libsodium/libsodium-android-*' 的文件状态(stat): 没有那个文件或目录
all of static libs move into /home/saaaaalty/Desktop/Dark/AESJniEncrypt/sodium_include.
```

**Comment by BruceWind** [comment]
```
cd aesjni/src/main/jni
bash ./build_libsodium_for_all_android_abi.sh
```

这样子呢

**Comment by BruceWind** [comment]
https://stackoverflow.com/questions/1236104/py2app-error-cant-copy-s-doesnt-exist-or-not-a-regular-file  好像是python问题。。。

**Comment by BruceWind** [comment]
我这里没法复现你的问题。非常抱歉！

**Comment by BruceWind** [comment]
"那么我直接将 libsodium 的源码搬运到对应目录下会有用吗？"
没用。必须要编译出静态连接库，放到指定目录。

**Comment by Mr-Spade** [comment]
我重新尝试了一下，发现原因在于ndk版本不对，现在sh脚本应该运行成功了。

不过不知道是否方便请教一个小问题，使用gradle build命令后出现如下提示：

```
* What went wrong:
Execution failed for task ':aesjni:generateJsonModelDebug'.
> /home/saaaaalty/Desktop/Light/AESJniEncrypt/aesjni/CMakeLists.txt : C/C++ debug|x86_64 : CMake Error at /home/saaaaalty/Desktop/Light/AESJniEncrypt/aesjni/CMakeLists.txt:20 (message):
    x86_64 static libraries might doesn't exist.
```

查看了一下，似乎是CMakeList.txt 中没有ANDROID_ABI为x86_64的选项，请问是该项目不支持，还是稍加修改将x86_64修改为x86的结果即可呢？

非常感谢！

**Comment by BruceWind** [comment]
生成的一个目录 XXX_include , 把这个目录移动到 aes/src/main/jni/ 下面

**Comment by Mr-Spade** [comment]
之前用的ndk包名是android-ndk-r10e，现在改成了android-ndk-r24-beta2-linux，这个包是在libsodium的说明文档里找到的

**Comment by Mr-Spade** [comment]
我已经找到了XXX_include文件夹并移动它，也看到.a文件了。

不过现在执行gradle build命令又出现新的错误提示：

```
* What went wrong:
Execution failed for task ':aesjni:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process /home/saaaaalty/Android/Sdk/cmake/3.10.2.4988404/bin/ninja with arguments {-C /home/saaaaalty/Desktop/Light/AESJniEncrypt/aesjni/.cxx/cmake/debug/armeabi-v7a JNIEncrypt}
  ninja: Entering directory `/home/saaaaalty/Desktop/Light/AESJniEncrypt/aesjni/.cxx/cmake/debug/armeabi-v7a'
  
  ninja: error: '../../../../src/main/jni/sodium_include/libsodium-android-armv7-a/lib/libsodium.a', needed by '../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libJNIEncrypt.so', missing and no known rule to make it

```
查看了一下../../../../build/intermediates/cmake/debug/obj/armeabi-v7a是空的，您对此有什么头绪吗？

我使用的是ubuntu虚拟机，不知道问题是不是与此有关？

**Comment by BruceWind** [comment]
`./aesjni/src/main/jni/sodium_include/libsodium-android-armv7-a/lib/libsodium.a`  这个文件有吗？

**Comment by Mr-Spade** [comment]
我的文件是`./aesjni/src/main/jni/sodium_include/libsodium-android-armv8-a/lib/libsodium.a`，但是没有`armv7-a`的文件夹

**Comment by BruceWind** [comment]
有V8 即可。

**Comment by BruceWind** [comment]
请尝试用NDK 16 -22之间的版本，其他版本我没测试过。

**Comment by Mr-Spade** [comment]
好的，但是gradle build不成功的话，我似乎没法打包apk

**Comment by Mr-Spade** [comment]
是有什么忽略这一错误的方法吗？

**Comment by BruceWind** [comment]
gradle 配置 可以限制ABI 到arm8 x86 等

**Comment by BruceWind** [comment]
> 是有什么忽略这一错误的方法吗？

你尝试换到 16-22 之间的NDK 试试。

**Comment by Mr-Spade** [comment]
根据您的建议修改了一下build.gradle，调整了一些版本号，现在成功编译了。谢谢！
